parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: pruebas
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 345bd5a55a96be392832fd541aebf631
    database_path: null
