security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Pruebas\YoBundle\Entity\Yo: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      chain_provider:
            chain:
                providers: [in_memory, usuario]
                
      usuario:
         entity: { class: Pruebas\YoBundle\Entity\Yo, property: nombre }

                
      in_memory:
            memory:
                users:                  
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:   ^/country
            form_login:
              login_path:             /login
              check_path:           /country/login_check
              
            anonymous:             ~ 
            logout:                      
                path:   /country/logout
                target: /country
            
            

          
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: /login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /country, roles: ROLE_USUARIO}
